import numpy as np
from pathlib import Path
import logging
from consts import ftype, ctype, C_LIGHT, AU2A, AU2EV, PI
from helper import readData, symmetrize_axial_tensor
#from kgrid import get_k_grid_and_spacing, setup_kq_grid_fd

logging.basicConfig(level=logging.INFO)

class BSE:
    """
    Represents BSE (Bethe-Salpeter Equation) data from the EXCEIG file generated by VASP's bse.F routine.

    Attributes
    ----------
    ncv : int
        BSE dimension (number of c-v-k combinations).
    table : NDArray[np.int32]
        Index table of shape (ncv, 4) with columns: [k-point, valence band, conduction band, spin].
    nkpts : int
        Number of unique k-points in the BSE calculation.
    nbandsv : int
        Number of unique valence bands.
    nbandsc : int
        Number of unique conduction bands.
    nspins : int
        Number of spin channels (1 or 2).
    lboundv : int
        Lowest valence band index.
    uboundv : int
        Highest valence band index.
    lboundc : int
        Lowest conduction band index.
    uboundc : int
        Highest conduction band index.
    kvecs : NDArray[np.float64]
        K-point coordinates used in BSE.
    k_to_ibz_index : NDArray[np.int32]
        Mapping of BSE k-points to the irreducible Brillouin zone (IBZ) indices.
    k_to_ibz_symop : NDArray[np.int32]
        Symmetry operations mapping k-points from IBZ to BSE k-points, shape (nkpts, 3, 3).
    k_to_ibz_tinv : NDArray[bool]
        Flags indicating time-reversal symmetry for k-point mappings.
    eig : NDArray[np.float64]
        BSE eigenvalues.
    """

    def __init__(self, filename = "EXCEIG"):
        """
        Initialize the BSE object by reading data from an EXCEIG file.

        Parameters
        ----------
        filename : str, optional
            Path to the EXCEIG binary file. Defaults to "EXCEIG".

        Raises
        ------
        FileNotFoundError
            If the specified file cannot be opened.
        ValueError
            If the data read does not conform to expected formats or sizes.
        """
        try:
            with open(filename, "rb") as fp:
                self._read_header(fp)
                self._read_index_table(fp)
                self._compute_band_and_spin_stats()
                self._read_kpoint_data(fp)
                self._read_mappings(fp)
                self._read_eigenvalues(fp)
        except FileNotFoundError:
            raise FileNotFoundError(f"Could not open BSE data file: {filename}")

    def _read_header(self, fp) -> None:
        """Read the BSE dimension (ncvk, neig) from the file."""
        self.ncv = readData(fp, np.int32)[0] 

    def _read_index_table(self, fp) -> None:
        """Read the BSE index table (k-point, valence, conduction, spin)."""
        self.table = np.zeros((self.ncv, 4), dtype=np.int32)
        for col in range(4):
            self.table[:, col] = readData(fp, np.int32)

    def _compute_band_and_spin_stats(self) -> None:
        """Compute statistics from the index table (unique counts and bounds)."""
        self.nkpts = len(np.unique(self.table[:, 0]))
        self.nbandsv = len(np.unique(self.table[:, 1]))
        self.nbandsc = len(np.unique(self.table[:, 2]))
        self.nspins = len(np.unique(self.table[:, 3]))

        valence_bands = np.unique(self.table[:, 1])
        self.lboundv = valence_bands[0]
        self.uboundv = valence_bands[-1]

        conduction_bands = np.unique(self.table[:, 2])
        self.lboundc = conduction_bands[0]
        self.uboundc = conduction_bands[-1]

        self.table2 = self.table.copy()
        self.table2[:, 0] = self.table2[:, 0] - 1
        self.table2[:, 1] = self.table2[:, 1] - self.lboundv  # Valence band indices
        self.table2[:, 2] = self.table2[:, 2] - self.lboundc  # Conduction band indices
        self.table2[:, 3] = self.table2[:, 3] - 1

    def _read_kpoint_data(self, fp) -> None:
        """Read k-point coordinates used in BSE."""
        self.kvecs = readData(fp, np.float64).reshape(self.nkpts, 3).astype(ftype, copy=False)

    def _read_mappings(self, fp) -> None:
        """Read k-point mappings and symmetry operations."""
        # Mapping BSE k-points to original full k-grid (IBZKPT_HF), adjusted for 0-based indexing
        k_to_org = readData(fp, np.int32) - 1

        # Mapping from full BZ to IBZ
        k_fbz_to_ibz_index = readData(fp, np.int32) - 1

        # Symmetry operations (3x3 matrices for each k-point) in crystal coords.
        # In VASP, ISYMOP(3, 3, n) and IGRPOP(3, 3, n) are for direct and reciprocal space.
        # IGRPOP(i,j,isym)*K(i) transforms K_IBZ from IBZ to equivalent K_FBZ in full BZ.
        symop_flat = readData(fp,np.int32)
        k_fbz_to_ibz_symop = symop_flat.reshape((self.nkpts, 3, 3))

        # Time-reversal flags (converted to Python boolean convention)
        # Fortran interprets True as -1 whereas Python does as 1. 
        k_fbz_to_ibz_tinv = readData(fp, np.int32) != 0

        # Compute final mappings
        self.k_to_ibz_index = k_fbz_to_ibz_index[k_to_org]
        self.k_to_ibz_symop = k_fbz_to_ibz_symop[k_to_org,...]
        self.k_to_ibz_tinv = k_fbz_to_ibz_tinv[k_to_org] 

    def _read_eigenvalues(self, fp) -> None:
        """Read BSE eigenvalues."""
        self.eig = readData(fp, np.float64).astype(ftype, copy=False)

    def convert_symop_cryst_to_cart(self, A) -> None:
        """Convert symmetry operations from crystal basis to Cartesian basis.
           A: lattice vector (row vector notation)
        """
        rotations = self.k_to_ibz_symop.astype(ftype)
        A_T = A.T
        A_T_INV = np.linalg.inv(A_T)
        self.k_to_ibz_symop = A_T @ rotations @ A_T_INV

    def read_bse_amplitude_single(self, filename = 'EXCWAV') -> np.ndarray:
        """
        Read exciton amplitude A_{cvk} from a binary file (e.g., EXCWAV).

        Parameters
        ----------
        filename : str, optional
            Path to the binary file containing BSE amplitudes. Defaults to "EXCWAV".
        dtype : numpy.dtype, optional
            Data type for the amplitude array. Defaults to np.complex64.

        Returns
        -------
        np.ndarray
            Reshaped array of exciton amplitudes with shape 
            (nexcs, nspins, nkpts, nbandsc, nbandsv).

        Raises
        ------
        AssertionError
            If the number of elements read (temp) does not match self.ncvk.
        FileNotFoundError
            If the specified file cannot be opened.
        """
        try:
            with open(filename, "rb") as f:
                temp, self.nexcs = readData(f,np.int32)
                if temp != self.ncv:
                    raise AssertionError(
                        f"Expected {self.ncv} elements, but got {temp}"
                    )
                acv = readData(f,dtype=np.complex64).astype(ctype, copy=False) # single precision A_cvk
        except FileNotFoundError:
            raise FileNotFoundError(f"Could not open file: {filename}")

        return acv.reshape(
            (self.nexcs, self.nspins, self.nkpts, self.nbandsc, self.nbandsv)
        )
    
    
    def read_bse_amplitude_multiple(self, file_prefix: str = 'EXCWAV') -> np.ndarray:
        """
        Read exciton amplitude A_{cvk} from binary files EXCWAV.* generated by each node.

        Parameters
        ----------
        file_prefix : str
            Prefix for the distributed EXCWAV binary files (e.g., 'EXCWAV').

        Returns
        -------
        np.ndarray
            A reshaped array of exciton amplitudes with dimensions
            (nexcs, nspins, nkpts, nbandsc, nbandsv).
        """
        # Initialize the amplitude array
        self.nexcs = self.ncv
        acv = np.zeros((self.ncv, self.nexcs), dtype=ctype)

        # Use pathlib for path operations and sorting numerically
        files = sorted(Path('.').glob(f"{file_prefix}.*"), key=lambda x: int(x.suffix[1:]))

        for file in files:
            try:
                with open(file, 'rb') as f:
                    logging.info(f"Processing {file.name}")

                    mb, nb, lld, nprow, npcol, myrow, mycol, np_local, nq_local = readData(f, np.int32)
                    i_global = readData(f, np.int32) - 1
                    j_global = readData(f, np.int32) - 1
                    amat_flat = readData(f, np.complex64).astype(ctype, copy=False)  # single precision A_cvk
                    amat = amat_flat.reshape((np_local, nq_local), order='F')
                
                    acv[np.ix_(i_global, j_global)] = amat

            except Exception as e:
                logging.error(f"Error reading {file.name}: {e}")
        
        # Reshape and return in the desired final format
        return acv.flatten(order="F").reshape(
            (self.nexcs, self.nspins, self.nkpts, self.nbandsc, self.nbandsv)
        )


    def unfold_bloch_dipole(self, rmn, linv) -> np.ndarray:
        """unfold matrix elements of bloch states from IBZ to FBZ

        Args:
            rmn: Matrix elements with shape (nspins, nk_IBZ, nb1, nb2, 3, [3]).
            ltinv: bool, True for velocity and magnetic dipole, 
                         False for electric dipole and pure quadrupole 
                         i*omega*Q should be True as well.

        Returns:
            rmn_full: Matrix elements with shape (nspins, nk_FBZ, nb1, nb2, 3, [3]). 

        Raises:
            ValueError: If the k-point mesh does not align with IBZKPT when nk_ibz != nkpts.
        """
        dim = list(rmn.shape)
        nk_ibz = dim[1]  # Number of irreducible k-points

        # Check if the number of k-points matches the full mesh
        if nk_ibz == self.nkpts:
            # Direct assign when k-points align
            rmn_full = rmn
        else:
            # Verify IBZ k-points align with the start of the full k-list
            if not np.all(self.k_to_ibz_index[:nk_ibz] == np.arange(nk_ibz)):
                raise ValueError(
                    "The first nk_ibz k-points in the full mesh must match IBZKPT!"
                )

            # Initialize full k-point array
            dim[1] = self.nkpts
            rmn_full = np.zeros(dim, dtype=ctype)
            rmn_full[:, :nk_ibz, ...] = rmn

            # Apply symmetry operations to unfold IBZ to full BZ
            rotations = self.k_to_ibz_symop[nk_ibz:, :, :].astype(ctype)
            unfolded_indices = self.k_to_ibz_index[nk_ibz:]
            rmn_ = rmn[:, unfolded_indices,...]
            ns, nk, nb1, nb2 = rmn_.shape[:4]
            if len(dim) == 5: 
                # rotation on vector V' = R V 
                #rmn_full[:, nk_ibz:, ...] = (
                #    np.einsum(
                #    'ijklm,jnm->ijkln',
                #    rmn_,
                #    rotations,
                #    optimize=True)
                #)
                # batched matmul faster than einsum
                rmn_full[:, nk_ibz:, ...] = (
                    rotations @
                    rmn_.transpose(1,4,0,2,3).reshape(nk,3,ns*nb1*nb2)
                    ).reshape(nk,3,ns,nb1,nb2).transpose(2,0,3,4,1)
            else:
                # rotation on matrix M' = R M R^-1, here R^-1 = R^T
                # two-step is faster than one-step for standard numpy

                #temp = np.einsum(
                #'ijk,limnko->limnjo',
                #rotations,
                #rmn_,
                #optimize=True
                #)
                #rmn_full[:, nk_ibz:, ...] = (
                #    np.einsum(
                #    'ijklmn,jon->ijklmo',
                #    temp,
                #    rotations,
                #    optimize=True)
                #)
                rmn_full[:, nk_ibz:, ...] = ((
                    rotations @
                    rmn_.transpose(1,4,0,2,3,5).reshape(nk,3,ns*nb1*nb2*3)
                    ).reshape(nk,3*ns*nb1*nb2,3)
                    @ rotations.swapaxes(1,2)
                    ).reshape(nk,3,ns,nb1,nb2,3).transpose(2,0,3,4,1,5)


                    
                # one-step
                #rmn_full[:, nk_ibz:, ...] = (
                #    np.einsum(
                #    'ijk,limnko,ipo->limnjp',
                #    rotations,
                #    rmn[:, unfolded_indices, ...],
                #    rotations,
                #    optimize=True)
                #)

            # Apply time-reversal symmetry where applicable
            tinv = np.where(self.k_to_ibz_tinv)[0]
            tinv_fbz = tinv[tinv >= nk_ibz]  # Only beyond IBZ
            if tinv_fbz.size > 0:
                tmp = rmn_full[:, tinv_fbz, ...].conj()
                rmn_full[:, tinv_fbz, ...] = -tmp if linv else tmp

        return rmn_full
    
    def calc_electric_multipole_ipa(self, rmn, vmn) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Calculate the multipole matrix elements.
        
        Args:
            rmn: Positioin matrix elements with shape (nspins, nk_IBZ, nbands, nbands, 3).
            vmn: Velocity matrix elements with shape (nspins, nk_IBZ, nbands, nbands, 3).

        Returns:
            v_cv: velocity matrix elements with shape (nspins, nk_FBZ, nc, nv, 3). 
            m_cv: Magnetic dipole matrix elements with shape (nspins, nk_FBZ, nc, nv, 3, 3). 
            q_cv: Electric quadrupole matrix elements with shape (nspins, nk_FBZ, nc, nv, 3, 3). 
        """
        # Extract band indices 
        c0, c1 = self.lboundc - 1, self.uboundc  # Conduction band range    
        v0, v1 = self.lboundv - 1, self.uboundv  # Valence band range   

        # Compute mixed tensor wcv: (nspins, nk_IBZ, nc, nv, 3, 3)
        # using symmetrized combination of position and velocity operators
        r1 = rmn[:,:,c0:c1,:,:]
        v_1 = vmn[:,:,:,v0:v1,:]
        v_2 = vmn[:,:,c0:c1,:,:]
        r2 = rmn[:,:,:,v0:v1,:]

        #wcv = (
        #    np.einsum('skmpi,skpnj->skmnij', r1, v_1, optimize=True) +
        #    np.einsum('skmpj,skpni->skmnij', v_2, r2, optimize=True)
        #) / 2

        nc = c1 - c0
        nv = v1 - v0
        ns, nk, nb = rmn.shape[:3]

        r1_ = r1.swapaxes(3,4).reshape(ns,nk,nc*3,nb)
        v1_ = v_1.reshape(ns,nk,nb,nv*3)
        v2_ = v_2.swapaxes(3,4).reshape(ns,nk,nc*3,nb)
        r2_ = r2.reshape(ns,nk,nb,nv*3)

        w_cv = (
            (r1_ @ v1_).reshape(ns,nk,nc,3,nv,3).swapaxes(3,4) +
            (v2_ @ r2_).reshape(ns,nk,nc,3,nv,3).transpose(0,1,2,4,5,3)
        )/2



        # Electric quadrupole tensor: symmetric part
        w_cv_T = w_cv.swapaxes(4,5)
        q_cv_ibz = (w_cv + w_cv_T) / 2

        # Magnetic dipole tensor: antisymmetric part
        m_cv_ibz = (w_cv - w_cv_T) / 2

        # Unfold from IBZ to FBZ 
        
        v_cv = self.unfold_bloch_dipole(vmn[:,:,c0:c1,v0:v1,:], linv=True)  # → shape: (nspins, nk_FBZ, nc, nv, 3, 3)
        m_cv = self.unfold_bloch_dipole(m_cv_ibz, linv=True)  # → shape: (nspins, nk_FBZ, nc, nv, 3, 3)
        q_cv = self.unfold_bloch_dipole(q_cv_ibz, linv=True)  # → shape: (nspins, nk_FBZ, nc, nv, 3, 3)

        return v_cv, m_cv, q_cv 
    
    def calc_electric_dipole(self, rmn, acv) -> np.ndarray:
        """Calculate the exciton dipole moment.

        The dipole is computed as:
            dipole = <Ψ_λ | r | 0> = Σ_{cvk} A_{cvk}^* r_{cvk},
        where r_{cvk} = <u_ck | r | u_vk> is the dipole matrix element between
        conduction and valence band states.

        Args:
            rmn: Dipole matrix elements with shape (nspins, nk_IBZ, nbands, nbands, 3) IBZ.
            acv: Exciton coefficients with shape (nexcs, nspins, nk_FBZ, nbandsc, nbandsv).

        Returns:
            Exciton dipole moment normalized by sqrt(nkpts), shape (nexcs, 3).

        """
        # Extract band indices 
        c0, c1 = self.lboundc - 1, self.uboundc  # Conduction band range
        v0, v1 = self.lboundv - 1, self.uboundv  # Valence band range

        # Slice dipole matrix for relevant bands
        rcv = rmn[:, :, c0:c1, v0:v1, :]  # Shape: (nspin, nkpts, nbandsc, nbandsv, 3)

        # unfold from IBZ to FBZ
        rcv_full = self.unfold_bloch_dipole(rcv, False)

        dipole = np.tensordot(
            acv.conj(), rcv_full, axes=([1, 2, 3, 4], [0, 1, 2, 3])
            )  # Shape: (nexcs, 3)

        # Normalize by sqrt(nkpts)
        norm = np.sqrt(self.nkpts, dtype=ctype)
        return dipole / norm

    def calc_velocity_matrix_element(self, vmn, acv) -> np.ndarray:
        """Calculate approximate velocity matrix element between exciton and ground state

        V_s0 = <Ψ_λ | v | 0> = Σ_{cvk} A_{cvk}^* v_{cvk},
        where v_{cvk} = <u_ck | v_k | u_vk> is the velocity matrix element between
        conduction band valence bands.

        Args:
            vmn: Velocity matrix elements with shape (nspins, nk_IBZ, nbands, nbands, 3) IBZ.
            acv: Exciton coefficients with shape (nexcs, nspins, nkpts, nbandsc, nbandsv).

        Returns:
            Exciton velocity matrix normalized by sqrt(nkpts), shape (nexcs, 3).

        """
        # Extract band indices 
        c0, c1 = self.lboundc - 1, self.uboundc  # Conduction band range
        v0, v1 = self.lboundv - 1, self.uboundv  # Valence band range

        # Slice velocity matrix for relevant bands
        vcv = vmn[:, :, c0:c1, v0:v1, :]  # Shape: (nspins, nk_IBZ, nbandsc, nbandsv, 3)

        # unfold from IBZ to FBZ
        vcv_full = self.unfold_bloch_dipole(vcv, True)

        velocity = np.tensordot(
            acv.conj(), vcv_full, axes=([1, 2, 3, 4], [0, 1, 2, 3])
            )  # Shape: (nexcs, 3)

        # Normalize by sqrt(nkpts)
        norm = np.sqrt(self.nkpts, dtype=ctype)
        return velocity / norm

    def calc_magnetic_dipole_electric_quadrupole(
        self, 
        rmn: np.ndarray, 
        vmn: np.ndarray, 
        acv: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Approximate exciton magnetic dipole and electric quadrupole moments.

        The moments are computed as:
            M = Σ_{cvk} A_{cvk}^* · m_{cvk}
            Q = Σ_{cvk} A_{cvk}^* · q_{cvk}
        where m_{cvk} and q_{cvk} are Bloch magentic dipole and electric quadrupole
        matrix elements derived from dipole (rmn) and velocity (vmn) matrices.

        Args:
            rmn (np.ndarray): Position matrix elements, shape (nspin, nk_IBZ, nb, nb, 3).
            vmn (np.ndarray): Velocity matrix elements, shape (nspin, nk_IBZ, nb, nb, 3).
            acv (np.ndarray): Exciton amplitude, shape (nexcs, nspin, nk_FBZ, nc, nv).

        Returns:
            Tuple[np.ndarray, np.ndarray]:
                - Magnetic dipole moment (M), shape (nexcs, 3)
                - Electric quadrupole moment (Q), shape (nexcs, 3, 3)
        """
        # Extract band index ranges
        c0, c1 = self.lboundc - 1, self.uboundc  # Conduction band range
        v0, v1 = self.lboundv - 1, self.uboundv  # Valence band range

        # Compute mixed tensor wcv: (nspins, nk_IBZ, nc, nv, 3, 3)
        # using symmetrized combination of position and velocity operators
        r1 = rmn[:,:,c0:c1,:,:]
        v_1 = vmn[:,:,:,v0:v1,:]
        v_2 = vmn[:,:,c0:c1,:,:]
        r2 = rmn[:,:,:,v0:v1,:]

        #wcv = (
        #    np.einsum('skmpi,skpnj->skmnij', r1, v_1, optimize=True) +
        #    np.einsum('skmpj,skpni->skmnij', v_2, r2, optimize=True)
        #) / 2

        nc = c1 - c0
        nv = v1 - v0
        ns, nk, nb = rmn.shape[:3]

        r1_ = r1.swapaxes(3,4).reshape(ns,nk,nc*3,nb)
        v1_ = v_1.reshape(ns,nk,nb,nv*3)
        v2_ = v_2.swapaxes(3,4).reshape(ns,nk,nc*3,nb)
        r2_ = r2.reshape(ns,nk,nb,nv*3)

        wcv = (
            (r1_ @ v1_).reshape(ns,nk,nc,3,nv,3).swapaxes(3,4) +
            (v2_ @ r2_).reshape(ns,nk,nc,3,nv,3).transpose(0,1,2,4,5,3)
        )/2



        # Electric quadrupole tensor: symmetric part
        wcv_T = wcv.swapaxes(4,5)
        qcv_ibz = (wcv + wcv_T) / 2

        # Magnetic dipole tensor: antisymmetric part
        mcv_ibz = (wcv - wcv_T) / 2

        # Unfold from IBZ to FBZ 
        
        mcv = self.unfold_bloch_dipole(mcv_ibz, linv=True)  # → shape: (nspins, nk_FBZ, nc, nv, 3, 3)
        qcv = self.unfold_bloch_dipole(qcv_ibz, linv=True)  # → shape: (nspins, nk_FBZ, nc, nv, 3, 3)

        # Contract with exciton coefficients A_cv: weighted sum over (s, k, c, v)
        M = np.tensordot(acv.conj(), mcv, axes=([1, 2, 3, 4], [0, 1, 2, 3]))  # → (nexcs, 3, 3)
        Q = np.tensordot(acv.conj(), qcv, axes=([1, 2, 3, 4], [0, 1, 2, 3]))  # → (nexcs, 3, 3)

        # Normalize by sqrt of total k-points
        norm = np.sqrt(self.nkpts, dtype=ctype)
        return M / norm, Q / norm

    def calc_natural_optical_activity(
        self,
        V: np.ndarray,
        M: np.ndarray,
        Q: np.ndarray,
        vol: ftype,
        nspinors: int = 1,
        emin=0,
        emax=10,
        ne=200,
        eta=0.1,
        rotations: np.ndarray = None
    ) -> None:
        """
        Compute the natural optical activity tensor γ(ω) of excitons.

        γ_ijl = - (4π e² / V ω² ℏ) ∑_{\lambda} [V_i* W_jl - V_j W_il*] * f(ω)
        OR + iCD = ω²/2c² * γ
        where:
            - f(ω) = 1/(ω - E + iη) - 1/(ω + E + iη)
            - V: exciton velocity dipole, shape (nexcs, 3)
            - M: magnetic dipole matrix elements, shape (nexcs, 3, 3)
            - Q: electric quadrupole matrix elements, shape (nexcs, 3, 3)
    
        Args:
            V (np.ndarray): Exciton velocity dipole, shape (nexcs, 3)
            M (np.ndarray): Magnetic dipole moments, shape (nexcs, 3, 3)
            Q (np.ndarray): Electric quadrupole moments, shape (nexcs, 3, 3)
            volume (float): Volume of the unit cell 
            emin (float): Minimum photon energy [eV]
            emax (float): Maximum photon energy [eV]
            ne (int): Number of energy grid points
            eta (float): Broadening parameter in energy denominator [eV]
            nspinors (int): Number of spinor components (1 or 2)
            rotations (np.ndarray, optional): Symmetry operations for symmetrization, shape (nr, 3, 3)
        """

        # Compute antisymmetric combinations V* M and V* Q
        vm = np.zeros_like(M)
        vq = np.zeros_like(M)

        eig = self.eig

        cyclic_idx = np.array([[1, 2, 0], [2, 0, 1]], dtype=np.int32)  # i, j pairs
        for l in range(3):
            i, j = cyclic_idx[0], cyclic_idx[1] # shape (3,)
            vm[:,:,l] = (V[:,i].conj()*M[:,l,j] - V[:,j]*M[:,l,i].conj())/eig[:,None]**2
            vq[:,:,l] = (V[:,i].conj()*Q[:,l,j] - V[:,j]*Q[:,l,i].conj())/eig[:,None]**2

        # Build energy grid and spectral function
        omega = np.linspace(emin, emax, ne, dtype=ftype)  # shape: (ne,)
        en = omega[:, None]      # shape: (ne, 1)
        f = 1 / (en - eig + 1j * eta) - 1 / (en + eig + 1j * eta)  # shape: (ne, nexcs)

        # Contract with real part of response tensors
        gamma_m = np.tensordot(f, vm.real.astype(ctype), axes=([1], [0]))  # shape: (ne, 3, 3)
        gamma_q = np.tensordot(f, vq.real.astype(ctype), axes=([1], [0]))  # shape: (ne, 3, 3)

        # Symmetrize if needed
        if rotations is not None:
            gamma_m = symmetrize_axial_tensor(gamma_m, rotations)
            gamma_q = symmetrize_axial_tensor(gamma_q, rotations)

        # Conversion factor to degree/mm from atomic units
        prefactor = -4 * PI / vol * 2 / nspinors / 2 / C_LIGHT**2 / AU2EV
        prefactor *= 180 / PI / AU2A * 1e7

        gamma_m = gamma_m.reshape(ne, 9) * en**2 * prefactor
        gamma_q = gamma_q.reshape(ne, 9) * en**2 * prefactor
        gamma_total = gamma_m + gamma_q

        # Save and store
        _save_gamma(gamma_m, omega, 'm')
        _save_gamma(gamma_q, omega, 'q')
        _save_gamma(gamma_total, omega, 'tot')

def _save_gamma(gamma, omega, kernel) -> None:
    header = '   E(eV)        YZX            YZY            YZZ            ZXX            ' \
           +   'ZXY            ZXZ            XYX            XYY            XYZ'
    fmt = '%10.5f' + '%20.8f'*9
    omega = omega[:, None]
    filr = np.concatenate((omega, gamma.real), axis=1)
    fili = np.concatenate((omega, gamma.imag), axis=1)
    np.savetxt('gamma_real_'+kernel+'.dat', filr, fmt=fmt, header=header)
    np.savetxt('gamma_imag_'+kernel+'.dat', fili, fmt=fmt, header=header)
