import numpy as np
from consts import ctype, ftype, PI, chalf, zhalf
from helper import readData
from mpi4py import MPI
import gc
import PyScalapack


scalapack = PyScalapack(
    "libmpi.so",
    "libmkl_core.so",
    "libmkl_intel_thread.so",
    "libmkl_intel_lp64.so",
    "libmkl_blacs_intelmpi_lp64.so",
    "libmkl_scalapack_lp64.so",
    "libiomp5.so"
)
# non threading
#scalapack = PyScalapack(
#    "libmpi.so",
#    "libmkl_core.so",
#    "libmkl_sequential.so",
#    "libmkl_intel_lp64.so",
#    "libmkl_blacs_intelmpi_lp64.so",
#    "libmkl_scalapack_lp64.so",
#)

if ctype == np.complex64:
    MPI_dtype = MPI.COMPLEX
    pgemr2d = scalapack.pcgemr2d
    pgemm = scalapack.pcgemm
    one = scalapack.c_one
    zero = scalapack.c_zero
    half = chalf
else:
    MPI_dtype = MPI.DOUBLE_COMPLEX
    pgemr2d = scalapack.pzgemr2d
    pgemm = scalapack.pzgemm
    one = scalapack.z_one
    zero = scalapack.z_zero
    half = zhalf


   
def read_bse_amplitude_scalapack(
        ncv,   
        comm: MPI.Comm,
        file_prefix: str = 'EXCWAV' 
    ):
    """
    Read exciton amplitude A_{cvk} from binary files EXCWAV.* generated by each node,
    parallelized using MPI.#
    Parameters
    ----------
    comm : MPI.Comm
    MPI communicator for coordinating parallel processes.#
    file_prefix : str
        Prefix for the distributed EXCWAV binary files (e.g., 'EXCWAV').#
    Returns
    -------
    """
    # Get MPI rank and size
    rank = comm.Get_rank()
    size = comm.Get_size()
    filename = f"{file_prefix}.{rank + 1}"  # assuming rank maps to file
    try:
        with open(filename, "rb") as f:
            mb, nb, lld, nprow, npcol, myrow, mycol, np_local, nq_local = readData(f, np.int32)
            nprocs = nprow * npcol
            if nprocs != size:
                raise AssertionError(
                    f"Expected {nprocs} MPI ranks, but got {size}"
                )
            # Read global indices   
            i_global = readData(f, np.int32) - 1
            j_global = readData(f, np.int32) - 1 

            nprow_new = 1
            npcol_new = size

            with(
                scalapack(b'C', nprow, npcol) as ctx_2d,
                scalapack(b'C', nprow_new, npcol_new) as ctx_1d
            ):
                if ctx_2d.myrow.value != myrow or ctx_2d.mycol.value != mycol:
                    raise AssertionError(
                        f"Expected MPI rank {rank} at ({myrow}, {mycol}), but got ({ctx_2d.myrow}, {ctx_2d.mycol})"
                    )
                acv = ctx_2d.array(ncv, ncv, mb, nb, dtype=ctype)
                if acv.local_m != np_local or acv.local_n != nq_local:
                    raise AssertionError(
                        f"Expected local dimensions ({np_local}, {nq_local}), but got ({acv.local_m}, {acv.local_n})"
                    )
                acv_flat = readData(f, np.complex64).astype(ctype, copy=False)
                acv.data[...] = acv_flat.reshape((np_local, nq_local), order='F')

                # Choose nb_new (block size for columns)
                nb_new = 64 # Start with 64, tune based on performance (e.g., 32, 128)
                mb_new = ncv
                acv_1d = ctx_1d.array(ncv, ncv, mb_new, nb_new, dtype=ctype)

                # Redistribute acv from 2D to 1D grid
                pgemr2d(
                    *(mb_new, nb_new),
                    *acv.scalapack_params(),
                    *acv_1d.scalapack_params(),
                    ctx_2d.ictxt
                )
                del acv
                gc.collect()
                # Example ScaLAPACK operation (if needed)
                if rank == 0:
                    print(f"Redistributed acv to 1D grid: local shape {acv_1d.data.shape} on rank {rank}.")             
        
    except FileNotFoundError:
        raise FileNotFoundError(f"Could not open file: {filename}")


def calc_electric_multipole_bse(
    table: np.ndarray,
    vcv: np.ndarray,
    mcv: np.ndarray,
    qcv: np.ndarray,
    comm: MPI.Comm,
    file_prefix: str = 'EXCWAV'
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    
    """Calculate multipole matrix elements from exciton amplitudes A_{cvk} read from binary files.
    Computes the exciton matrix element: M = <Ψ_λ | \hat{m} | 0> = Σ_{cvk} A_{cvk}^* m_{cvk},
    where m_{cvk} = <u_ck | \hat{m} | u_vk> is the matrix element between conduction and valence band states.
    Args:
        vcv: Velocity matrix elements, shape (nspins, nk_FBZ, nbandsc, nbandsv, 3).
        mcv: Magnetic dipole matrix elements, shape (nspins, nk_FBZ, nbandsc, nbandsv, 3, 3).
        qcv: Electric quadrupole matrix elements, shape (nspins, nk_FBZ, nbandsc, nbandsv, 3, 3).
        comm: MPI communicator for parallel processes.
        file_prefix: Prefix for EXCWAV binary files (default: 'EXCWAV').
    Returns:
        tuple: (V, M, Q) where
            - V: Velocity matrix element, shape (nexcs, 3).
            - M: Magnetic dipole matrix element, shape (nexcs, 3, 3).
            - Q: Electric quadrupole matrix element, shape (nexcs, 3, 3).
    """

    rank = comm.Get_rank()
    size = comm.Get_size()

    # Read binary file
    filename = f"{file_prefix}.{rank + 1}"
    try:
        with open(filename, "rb") as f:
            # Read metadata
            metadata = readData(f, np.int32)
            mb, nb, lld, nprow, npcol, myrow, mycol, np_local, nq_local = metadata
            if nprow * npcol != size:
                raise ValueError(f"Expected {nprow * npcol} MPI ranks, got {size}")
            # Read global indices and amplitudes
            i_glb = readData(f, np.int32) - 1
            j_glb = readData(f, np.int32) - 1
            acv_flat = readData(f, np.complex64).astype(ctype, copy=False)  # single precision A_cvk
            acv = acv_flat.reshape((np_local, nq_local), order='F')  # F-order
    except FileNotFoundError:
        raise FileNotFoundError(f"Could not open file: {filename}")
    
    # Extract indices
    ids = table[i_glb, 3]  # Spin indices
    idk = table[i_glb, 0]  # k-point indices
    idv = table[i_glb, 1]  # Valence band indices
    idc = table[i_glb, 2]  # Conduction band indices

    # Compute local matrix elements (in-place conjugate transpose)
    acv_conj_T = acv.conj().T  # C-order (nexcs, ncv)
    mcv_rsp = mcv[ids, idk, idc, idv, :, :].reshape(np_local, 9)
    qcv_rsp = qcv[ids, idk, idc, idv, :, :].reshape(np_local, 9)
    V_local = np.dot(acv_conj_T, vcv[ids, idk, idc, idv, :])  # (nq_local, 3)
    M_local = np.dot(acv_conj_T, mcv_rsp).reshape(nq_local, 3, 3)  # (nq_local, 3, 3)
    Q_local = np.dot(acv_conj_T, qcv_rsp).reshape(nq_local, 3, 3)  # (nq_local, 3, 3)
    del acv, acv_conj_T
    gc.collect()

    # Split communicator into column communicators
    col_comm = comm.Split(color=mycol, key=myrow)
    col_rank = col_comm.Get_rank()

    # Initialize column sum arrays
    V_colsum = np.zeros_like(V_local, dtype=ctype)
    M_colsum = np.zeros_like(M_local, dtype=ctype)
    Q_colsum = np.zeros_like(Q_local, dtype=ctype)

    # Reduce local results to column root
    for local, colsum in [(V_local, V_colsum), (M_local, M_colsum), (Q_local, Q_colsum)]:
        col_comm.Reduce([local, MPI_dtype], [colsum, MPI_dtype], op=MPI.SUM, root=0)

    # Create root communicator for column roots
    root_comm = comm.Split(color=0 if col_rank == 0 else MPI.UNDEFINED, key=mycol)
    V = M = Q = None
    if root_comm != MPI.COMM_NULL:
        root_rank = root_comm.Get_rank()
        if rank == 0 and root_rank != 0:
            raise ValueError(f"Expected rank {rank}, got {root_rank}")
        
        # Gather nq_local from all column roots
        nq_local_all = root_comm.allgather(nq_local)
        nexcs = sum(nq_local_all)
        
        V_global = np.zeros((nexcs, 3), dtype=ctype)
        M_global = np.zeros((nexcs, 3, 3), dtype=ctype)
        Q_global = np.zeros((nexcs, 3, 3), dtype=ctype)
        V_global[j_glb,:] = V_colsum
        M_global[j_glb,:,:] = M_colsum
        Q_global[j_glb,:,:] = Q_colsum

        # Initialize global arrays on root
        if root_rank == 0:
            V = np.zeros((nexcs, 3), dtype=ctype)
            M = np.zeros((nexcs, 3, 3), dtype=ctype)
            Q = np.zeros((nexcs, 3, 3), dtype=ctype)

        root_comm.Reduce([V_global, MPI_dtype], [V, MPI_dtype], op=MPI.SUM, root=0)
        root_comm.Reduce([M_global, MPI_dtype], [M, MPI_dtype], op=MPI.SUM, root=0)
        root_comm.Reduce([Q_global, MPI_dtype], [Q, MPI_dtype], op=MPI.SUM, root=0)
        root_comm.Free()

    col_comm.Free()
 
    nkpoints = vcv.shape[1]  # Number of k-points
    norm = np.sqrt(nkpoints, dtype=ctype)

    if rank == 0:
        return V/norm, M/norm, Q/norm
    else:
        return np.zeros_like(V), np.zeros_like(M), np.zeros_like(Q)

def calc_electric_multipole_bse_scal(
    vcv: np.ndarray,
    mcv: np.ndarray,
    qcv: np.ndarray,
    comm: MPI.Comm,
    file_prefix: str = 'EXCWAV'
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    
    """Calculate multipole matrix elements from exciton amplitudes A_{cvk} read from binary files.
    Computes the exciton matrix element: M = <Ψ_λ | \hat{m} | 0> = Σ_{cvk} A_{cvk}^* m_{cvk},
    where m_{cvk} = <u_ck | \hat{m} | u_vk> is the matrix element between conduction and valence band states.
    Args:
        vcv: Velocity matrix elements, shape (nspins, nk_FBZ, nbandsc, nbandsv, 3).
        mcv: Magnetic dipole matrix elements, shape (nspins, nk_FBZ, nbandsc, nbandsv, 3, 3).
        qcv: Electric quadrupole matrix elements, shape (nspins, nk_FBZ, nbandsc, nbandsv, 3, 3).
        comm: MPI communicator for parallel processes.
        file_prefix: Prefix for EXCWAV binary files (default: 'EXCWAV').
    Returns:
        tuple: (V, M, Q) where
            - V: Velocity matrix element, shape (nexcs, 3).
            - M: Magnetic dipole matrix element, shape (nexcs, 3, 3).
            - Q: Electric quadrupole matrix element, shape (nexcs, 3, 3).
    """

    rank = comm.Get_rank()
    size = comm.Get_size()
    ns, nk, nc, nv = vcv.shape[:4]
    ncv = ns*nk*nc*nv

    # Read binary file
    filename = f"{file_prefix}.{rank + 1}"
    try:
        with open(filename, "rb") as f:
            # Read metadata
            metadata = readData(f, np.int32)
            mb, nb, lld, nprow, npcol, myrow, mycol, np_local, nq_local = metadata
            if nprow * npcol != size:
                raise ValueError(f"Expected {nprow * npcol} MPI ranks, got {size}")
            # Read global indices and amplitudes
            i_glb = readData(f, np.int32) - 1
            j_glb = readData(f, np.int32) - 1
            acv = readData(f, np.complex64).reshape((np_local, nq_local), order='F')  # F-order
    except FileNotFoundError:
        raise FileNotFoundError(f"Could not open file: {filename}")
    
    # Redistribute A_cvk from 2D grid to 1D grid over the exciton states

    nprow_new = 1
    npcol_new = size
    nb_new = 64 # Start with 64, tune based on performance (e.g., 32, 128)
    mb_new = ncv

    with (
        scalapack(b'C', nprow, npcol) as ctx_2d,
        scalapack(b'C', nprow_new, npcol_new) as ctx_1d
    ):
        if ctx_2d.myrow.value != myrow or ctx_2d.mycol.value != mycol:
            raise AssertionError(
                f"Expected MPI rank {rank} at ({myrow}, {mycol}), but got ({ctx_2d.myrow}, {ctx_2d.mycol})"
            )
        a2d = ctx_2d.array(ncv, ncv, mb, nb, dtype=ctype)
        if a2d.local_m != np_local or a2d.local_n != nq_local:
            raise AssertionError(
                f"Expected local dimensions ({np_local}, {nq_local}), but got ({a2d.local_m}, {a2d.local_n})"
            )
        a2d.data[...] = acv
        del acv
        gc.collect()

        a1d = ctx_1d.array(ncv, ncv, mb_new, nb_new, dtype=ctype)
        # Redistribute acv from 2D to 1D grid
        pgemr2d(
            *(ncv, ncv),
            *a2d.scalapack_params(),
            *a1d.scalapack_params(),
            ctx_1d.ictxt,
        )
        del a2d
        gc.collect()

        ncv_loc = a1d.local_n
        # Check carefully the meaning of order of numpy.reshape
        acv = a1d.data.reshape(-1, order='F').reshape(ncv_loc, ns, nk, nc, nv, order='C')
        del a1d
        gc.collect()

        # Global column index
        j_loc = np.arange(ncv_loc, dtype=np.int32) # Local column index
        j_loc_b = j_loc // nb_new # Local block index
        j_glb_b = j_loc_b * npcol_new + ctx_1d.mycol.value # Global block index
        j_in_block = j_loc % nb_new # Offset within block
        j_glb = j_glb_b * nb_new + j_in_block # Global column index

    # Contract with exciton coefficients A_cv: weighted sum over (s, k, c, v)
    V_local = np.tensordot(acv.conj(), vcv, axes=([1, 2, 3, 4], [0, 1, 2, 3]))
    M_local = np.tensordot(acv.conj(), mcv, axes=([1, 2, 3, 4], [0, 1, 2, 3]))
    Q_local = np.tensordot(acv.conj(), qcv, axes=([1, 2, 3, 4], [0, 1, 2, 3]))

    del acv
    gc.collect()

    V = np.zeros((ncv, 3), dtype=ctype)
    M = np.zeros((ncv, 3, 3), dtype=ctype)
    Q = np.zeros((ncv, 3, 3), dtype=ctype)
    V[j_glb] = V_local
    M[j_glb] = M_local
    Q[j_glb] = Q_local

    if rank == 0:
        comm.Reduce(MPI.IN_PLACE, [V, MPI_dtype], op=MPI.SUM, root=0)
        comm.Reduce(MPI.IN_PLACE, [M, MPI_dtype], op=MPI.SUM, root=0)
        comm.Reduce(MPI.IN_PLACE, [Q, MPI_dtype], op=MPI.SUM, root=0)
    else:
        comm.Reduce([V, MPI_dtype], None, op=MPI.SUM, root=0)
        comm.Reduce([M, MPI_dtype], None, op=MPI.SUM, root=0)
        comm.Reduce([Q, MPI_dtype], None, op=MPI.SUM, root=0)
    
    norm = np.sqrt(nk, dtype=ctype)

    return V/norm, M/norm, Q/norm
